### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bufolab** [noxasch/flutter_app_widget#18]
**Describe the bug**
Package name is not passed through the methods getWidgetIds and reloadWidget

**To Reproduce**
Initialize AppWidget with a different packageName (this can happen if package name of widget is not exactly the same as the global App).
Call getWidgetIds or reloadWidget

**Expected behavior**
Widget provider is found.

**Solution**
Add this line:
 'androidPackageName': androidPackageName,

 in file app_widget_android_plugin.dart in methods getWidgetIds and reloadWidgets to pass the parameter. So it will look like:

Line 73
    final widgetIds =
        await _methodChannel.invokeMethod<List<dynamic>?>('getWidgetIds', {
      'androidProviderName': androidProviderName,
      'androidPackageName': androidPackageName,
    });

Line 92
    return _methodChannel.invokeMethod<bool>(
      'reloadWidgets',
      {'androidProviderName': androidProviderName,
       'androidPackageName': androidPackageName,},
    );

**Comment by noxasch** [comment]
Hi @bufolab, do you have any working example app or any example use cases ?

**Comment by bufolab** [comment]
Yes.
If the developer sets a different package name for its widget provider, then it will fall into the user case.
Since the package API des not take into account the passed parameter "androidPackageName" it will use the Aplicacion package name, which it might be different from the widget provider package name. Thus, not finding it.

It looks like the API was ready take the "androidPackageName" as parameter but it simply was not using it.
I was trying to create a branch but I could not since I dont' have right, is there any way I can create a branch and pull request?

**Comment by noxasch** [comment]
Is this a common thing when developing android widget ?

If it common, then we would have to update all the api interface to allow the same behavior. I will take a look at this somewhere after new year. If you would like to contribute, you can fork the repo and create a branch in your fork. Then send a PR from your fork.
