### ISSUE TITLE
Redrawing the widget for each text

### ISSUE THREAD

**Issue by ruwiss** [noxasch/flutter_app_widget#22]
If there are 5 textviews, in the "update" operation
setting textview1 value -> updating widget.
setting textview2 value -> updating widget.
...

This is very wrong. Android doesn't support fast widget update anyway.
It should set all values first and update once.

**Comment by noxasch** [comment]
Hi @ruwiss will look into this. But I'm also open for a pull request as long as it accompanied with a test suite.
